# Copyright 2025 Dotanuki Labs
# SPDX-License-Identifier: MIT

version = 1

[[analyzers]]
name = "rust"
enabled = true

[analyzers.meta]
msrv = "1.75"
cyclomatic_complexity_threshold = "medium"

[[analyzers]]
name = "shell"
enabled = true
