[advisories]
ignore = [
    # Both better-panic and human-panic depend
    # indirectly on
    # https://github.com/jonas-schievink/adler
    # which is no longer maintened
    "RUSTSEC-2025-0056"
]

[licenses]
confidence-threshold = 0.95
allow = [
    "Apache-2.0",
    "MIT",
    "Unicode-3.0",
    "ISC",
    "BSD-3-Clause",
    "CDLA-Permissive-2.0"
]


# From https://embarkstudios.github.io/cargo-deny/checks/licenses/cfg.html
[[licenses.clarify]]
name = "ring"
expression = "MIT AND ISC AND OpenSSL"
license-files = [
    { path = "LICENSE", hash = 0xbd0eed23 }
]

