[advisories]
ignore = [
    # Already patched, no impact on this project
    # https://github.com/algesten/ureq/pull/748
    "RUSTSEC-2024-0336",
]

[licenses]
confidence-threshold = 0.95
allow = [
    "Apache-2.0",
    "MIT",
    "Unicode-DFS-2016",
    "ISC",
    "BSD-3-Clause",
    "MPL-2.0",
    "OpenSSL",
]


# From https://embarkstudios.github.io/cargo-deny/checks/licenses/cfg.html
[[licenses.clarify]]
name = "ring"
expression = "MIT AND ISC AND OpenSSL"
license-files = [{ path = "LICENSE", hash = 0xbd0eed23 }]
