[advisories]
ignore = [
    # No advisories so far!
]

[licenses]
confidence-threshold = 0.95
allow = [
    "Apache-2.0",
    "MIT",
    "Unicode-DFS-2016",
    "Unicode-3.0",
    "ISC",
    "BSD-3-Clause",
    "MPL-2.0",
    "OpenSSL"
]


# From https://embarkstudios.github.io/cargo-deny/checks/licenses/cfg.html
[[licenses.clarify]]
name = "ring"
expression = "MIT AND ISC AND OpenSSL"
license-files = [
    { path = "LICENSE", hash = 0xbd0eed23 }
]

