# Copyright 2025 Dotanuki Labs
# SPDX-License-Identifier: MIT

[advisories]
ignore = [
    "RUSTSEC-2026-0098",
    "RUSTSEC-2026-0099",
]

[licenses]
confidence-threshold = 0.95
allow = [
    "Apache-2.0",
    "MIT",
    "Unicode-3.0",
    "ISC",
    "BSD-3-Clause",
    "CDLA-Permissive-2.0",
]


# From https://embarkstudios.github.io/cargo-deny/checks/licenses/cfg.html
[[licenses.clarify]]
name = "ring"
expression = "MIT AND ISC"
license-files = [
    { path = "LICENSE", hash = 0xbd0eed23 }
]

