# Copyright 2025 Dotanuki Labs
# SPDX-License-Identifier: MIT

# Adapted from https://github.com/rust-lang/rust-clippy/blob/master/rustfmt.toml

edition = "2021"
max_width = 120
match_block_trailing_comma = true
