# Copyright 2025 Dotanuki Labs
# SPDX-License-Identifier: MIT

[target.'cfg(all())']
rustflags = [
    # Extended checks for clippy
    "-Dunsafe_code",
    "-Wclippy::all",
    "-Wclippy::todo",
    "-Wclippy::unimplemented",
    "-Wclippy::unnested_or_patterns",
    "-Wclippy::zero_sized_map_values",
    "-Wfuture_incompatible",
    "-Wnonstandard_style",
    "-Wrust_2018_idioms",
]

[target.x86_64-unknown-linux-musl]
linker = "rust-lld"
rustflags = ["-Ctarget-feature=+crt-static"]

[target.aarch64-unknown-linux-musl]
linker = "aarch64-linux-gnu-gcc"
rustflags = ["-Ctarget-feature=+crt-static"]
