# Copyright 2025 Dotanuki Labs
# SPDX-License-Identifier: MIT

name: CD

on: workflow_dispatch

permissions:
  id-token: write
  packages: write
  contents: read
  attestations: write

jobs:
  build-binaries:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-24.04", "macos-15"]

    steps:
      - name: Project Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup CI
        uses: ./.github/actions/setup-rust

      - name: Cross-compilation supported targets
        run: ./krabby.sh assemble

      - name: Archive binaries
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: gwv-binaries-${{ runner.os }}
          path: artifacts

  publish-github-release:
    needs: build-binaries
    runs-on: ubuntu-24.04

    steps:
      - name: Project Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup CI
        uses: ./.github/actions/setup-rust

      - name: Generate SBOM
        run: ./krabby.sh sbom

      - name: Fetch executable from previous build
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          path: artifacts
          pattern: gwv-binaries-*

      - name: Build provenance for binaries
        uses: actions/attest-build-provenance@a2bbfa25375fe432b6a289bc6b6cd05ecd0c4c32 # v4.1.0
        with:
          subject-path: artifacts/**/*

      - name: Prepare Github release
        id: prepare-release
        run: ./krabby.sh prepare-github-release

      - name: Publish draft release on Github
        uses: softprops/action-gh-release@153bb8e04406b158c6c84fc1615b65b24149a1fe # v2.6.1
        with:
          name: ${{ steps.prepare-release.outputs.version }}
          tag_name: ${{ steps.prepare-release.outputs.version }}
          token: ${{ secrets.DOTANUKI_BOT_TOKEN }}
          generate_release_notes: true
          draft: true
          files: |
            artifacts/**/*
            gwv.cdx.json

  push-docker-images:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner: ["ubuntu-24.04", "ubuntu-24.04-arm"]

    steps:
      - name: Project Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Compute release version
        id: prepare-release
        run: ./krabby.sh prepare-docker-release

      - name: Docker metadata
        id: docker-metadata
        uses: docker/metadata-action@030e881283bb7a6894de51c315a6bfe6a94e05cf # v6
        with:
          images: ghcr.io/${{ github.repository }}

      - name: Set up docker-buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4.0.0

      - name: Log in to Github Container Registry
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build container Image
        id: build
        uses: docker/build-push-action@d08e5c354a6adb9ed34480a06d141179aa583294 # v7.0.0
        with:
          context: .
          push: true
          provenance: false
          platforms: linux/${{ steps.prepare-release.outputs.platform }}
          labels: ${{ steps.docker-metadata.outputs.labels }}
          annotations: ${{ steps.docker-metadata.outputs.annotations }}
          outputs: type=registry,push=true
          tags: ghcr.io/${{ github.repository }}:${{ steps.prepare-release.outputs.version }}-${{ steps.prepare-release.outputs.platform }}

  publish-multiarch-docker-image:
    runs-on: ubuntu-24.04
    needs: push-docker-images

    steps:
      - name: Project Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Compute release version
        id: prepare-release
        run: ./krabby.sh prepare-docker-release

      - name: Log in to Github Container Registry
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Docker manifest
        run: ./krabby.sh docker-manifest ${{ steps.prepare-release.outputs.version }}

  publish-crate:
    needs: [publish-github-release, publish-multiarch-docker-image]
    runs-on: ubuntu-24.04

    steps:
      - name: Project Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup CI
        uses: ./.github/actions/setup-rust

      - name: Publish on crates.io
        run: cargo publish --token ${{ secrets.CRATESIO_PUBLISH_TOKEN }}
